### ratings.data - 영화평점 데이터
- loadtxt()
- delimiter
- dtype

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# userid, movieid, rating, timestamp
data = np.loadtxt('./data/ratings.dat', delimiter="::", dtype=np.int64)
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [3]:
def aryInfo(ary) :
    print('type : {}'.format(type(ary)))
    print('shape : {}'.format(ary.shape))
    print('dimension : {}'.format(ary.ndim))
    print('dtype : {}'.format(ary.dtype))
    print("Array Data :\n", ary)

In [4]:
aryInfo(data)

type : <class 'numpy.ndarray'>
shape : (1000209, 4)
dimension : 2
dtype : int64
Array Data :
 [[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


## 문제
- 데이터의 첫 5 행만 확인

- 데이터의 형태 확인

- 전체 평균 평점 계산
- data[ : , :2] 전체 행, 2번 열


- 사용자 아이디 수집
- 전체 행 , 0번 열
- 사용자별 평점 확인 >list로 만들기
- 사용자 아이디별 평점 확인


- 리스트를 Numpy 배열로 변환


In [5]:
print('1. 데이터의 첫 5 행만 확인')
# numpy의 matrix
data[ : 5, : ]

1. 데이터의 첫 5 행만 확인


array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [6]:
print('2. 데이터의 형태 확인')
data.shape

2. 데이터의 형태 확인


(1000209, 4)

In [7]:
print('3. 전체 평균 평점 계산')
mean_rating = data[ :, 2].mean()
print(mean_rating)

3. 전체 평균 평점 계산
3.581564453029317


In [8]:
print('4. 사용자 아이디 수집')
user_ids = np.unique(data[ :, 0])
user_ids

4. 사용자 아이디 수집


array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [11]:
print('5. 사용자별 평점 확인')
mean_userids = []
for user in user_ids :
    data_for_user = data[user == data[:, 0], :]
#     print(data_for_user)
    user_mean = data_for_user[ :, 2].mean()
#     print(user_mean)
    mean_userids.append([user, user_mean])
    
mean_userids[ : 5]

5. 사용자별 평점 확인


[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466]]

In [13]:
type(mean_userids[ :5])

list

In [14]:
print('6. 리스트를 Numpy 배열로 변환')
mean_userids_array = np.array(mean_userids, dtype=np.float32)
print(mean_userids_array[ : 5])
print(mean_userids_array.shape)
print(type(mean_userids_array))

6. 리스트를 Numpy 배열로 변환
[[1.        4.188679 ]
 [2.        3.7131784]
 [3.        3.9019608]
 [4.        4.1904764]
 [5.        3.1464646]]
(6040, 2)
<class 'numpy.ndarray'>


In [16]:
# csv 파일 저장
np.savetxt('./data/movies_mean_userids.csv', mean_userids_array, delimiter = ',', fmt = '%.1f')